OKX-handling-fetch-accounts-info
CornixIO/ccxt pull request #24
Opened 2023-12-18 13:19 UTC by dinmeiri

2023-12-20 07:09 UTC, dinmeiri commented on python/ccxt/okx.py
> +                'ip_restrict': not ips,
Tried searching for the usages of 'ip_restrict' and couldn't find any

2024-01-14 13:55 UTC, giladcornix requested changes

2024-01-14 13:55 UTC, giladcornix commented on python/ccxt/okx.py
> +                'ip_restrict': not ips,
'ip_restrict': bool(ips),

2024-01-14 14:40 UTC, giladcornix approved these changes

2024-01-14 14:40 UTC, merged